version: '3.9'

services:
  db:
    image: postgres:15.0-alpine3.16
    # image: postgres:13.4-buster
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - TZ=America/Asuncion
    volumes:
      - db:/var/lib/postgresql/data
    # restart: always

  pgadmin:
    image: dpage/pgadmin4:6.15
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80

  pictshare:
    image: hascheksolutions/pictshare:72394f17
    ports:
      - ${PICTSHARE_PORT}:80
    volumes:
      - pictshare:/usr/share/nginx/html/data

volumes:
  db:
  pictshare:
